'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.81.0.
'
Namespace ZefaniaXml2014
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class xmlbible
        
        Private prologField As Object
        
        Private biblebookField() As biblebook
        
        Private languageField As String
        
        '''<remarks/>
        Public Property prolog() As Object
            Get
                Return Me.prologField
            End Get
            Set
                Me.prologField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("biblebook")>  _
        Public Property biblebook() As biblebook()
            Get
                Return Me.biblebookField
            End Get
            Set
                Me.biblebookField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="language")>  _
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class biblebook
        
        Private prologField As Object
        
        Private chapterField() As chapter
        
        Private bookField As TBooks
        
        '''<remarks/>
        Public Property prolog() As Object
            Get
                Return Me.prologField
            End Get
            Set
                Me.prologField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("chapter")>  _
        Public Property chapter() As chapter()
            Get
                Return Me.chapterField
            End Get
            Set
                Me.chapterField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property book() As TBooks
            Get
                Return Me.bookField
            End Get
            Set
                Me.bookField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class chapter
        
        Private itemsField() As Object
        
        Private itemsElementNameField() As ItemsChoiceType1
        
        Private bookField As TBooks
        
        Private cnField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("headline", GetType(Object)),  _
         System.Xml.Serialization.XmlElementAttribute("paragraph", GetType(paragraph)),  _
         System.Xml.Serialization.XmlElementAttribute("prolog", GetType(Object)),  _
         System.Xml.Serialization.XmlElementAttribute("remark", GetType(Object)),  _
         System.Xml.Serialization.XmlElementAttribute("verse", GetType(verse)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType1()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property book() As TBooks
            Get
                Return Me.bookField
            End Get
            Set
                Me.bookField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
        Public Property cn() As String
            Get
                Return Me.cnField
            End Get
            Set
                Me.cnField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class paragraph
        
        Private itemsField() As Object
        
        Private itemsElementNameField() As ItemsChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("headline", GetType(Object)),  _
         System.Xml.Serialization.XmlElementAttribute("remark", GetType(Object)),  _
         System.Xml.Serialization.XmlElementAttribute("verse", GetType(verse)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class verse
        
        Private itemsField() As emphasis
        
        Private textField() As String
        
        Private bookField As TBooks
        
        Private cnField As String
        
        Private vnField As String
        
        Private ixField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("emphasis")>  _
        Public Property Items() As emphasis()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property book() As TBooks
            Get
                Return Me.bookField
            End Get
            Set
                Me.bookField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
        Public Property cn() As String
            Get
                Return Me.cnField
            End Get
            Set
                Me.cnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
        Public Property vn() As String
            Get
                Return Me.vnField
            End Get
            Set
                Me.vnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
        Public Property ix() As String
            Get
                Return Me.ixField
            End Get
            Set
                Me.ixField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class emphasis
        
        Private itemsField() As emphasis
        
        Private textField() As String
        
        Private idField As TEmphasis
        
        Private xdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("emphasis")>  _
        Public Property Items() As emphasis()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property id() As TEmphasis
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property xd() As String
            Get
                Return Me.xdField
            End Get
            Set
                Me.xdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum TEmphasis
        
        '''<remarks/>
        acrostic
        
        '''<remarks/>
        bold
        
        '''<remarks/>
        lookup
        
        '''<remarks/>
        crossreference
        
        '''<remarks/>
        illuminated
        
        '''<remarks/>
        italic
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("line-through")>  _
        linethrough
        
        '''<remarks/>
        normal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("small-caps")>  _
        smallcaps
        
        '''<remarks/>
        [sub]
        
        '''<remarks/>
        super
        
        '''<remarks/>
        underline
        
        '''<remarks/>
        overline
        
        '''<remarks/>
        capitalize
        
        '''<remarks/>
        uppercase
        
        '''<remarks/>
        lowercase
        
        '''<remarks/>
        divineName
        
        '''<remarks/>
        small
        
        '''<remarks/>
        added
        
        '''<remarks/>
        allusion
        
        '''<remarks/>
        alternative
        
        '''<remarks/>
        background
        
        '''<remarks/>
        citation
        
        '''<remarks/>
        devotional
        
        '''<remarks/>
        encoder
        
        '''<remarks/>
        exegesis
        
        '''<remarks/>
        explanation
        
        '''<remarks/>
        liturgical
        
        '''<remarks/>
        speaker
        
        '''<remarks/>
        study
        
        '''<remarks/>
        translation
        
        '''<remarks/>
        [variant]
        
        '''<remarks/>
        amplified
        
        '''<remarks/>
        changed
        
        '''<remarks/>
        deleted
        
        '''<remarks/>
        implied
        
        '''<remarks/>
        moved
        
        '''<remarks/>
        tenseChange
        
        '''<remarks/>
        commentary
        
        '''<remarks/>
        exposition
        
        '''<remarks/>
        meditation
        
        '''<remarks/>
        outline
        
        '''<remarks/>
        rebuttal
        
        '''<remarks/>
        sermon
        
        '''<remarks/>
        studyGuide
        
        '''<remarks/>
        transChange
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum TBooks
        
        '''<remarks/>
        GEN
        
        '''<remarks/>
        EXO
        
        '''<remarks/>
        LEV
        
        '''<remarks/>
        NUM
        
        '''<remarks/>
        DEU
        
        '''<remarks/>
        JOS
        
        '''<remarks/>
        JDG
        
        '''<remarks/>
        RUT
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1SA")>  _
        Item1SA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2SA")>  _
        Item2SA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1KI")>  _
        Item1KI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2KI")>  _
        Item2KI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1CH")>  _
        Item1CH
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2CH")>  _
        Item2CH
        
        '''<remarks/>
        EZR
        
        '''<remarks/>
        NEH
        
        '''<remarks/>
        EST
        
        '''<remarks/>
        JOB
        
        '''<remarks/>
        PSA
        
        '''<remarks/>
        PRO
        
        '''<remarks/>
        ECC
        
        '''<remarks/>
        SNG
        
        '''<remarks/>
        ISA
        
        '''<remarks/>
        JER
        
        '''<remarks/>
        LAM
        
        '''<remarks/>
        EZK
        
        '''<remarks/>
        DAN
        
        '''<remarks/>
        HOS
        
        '''<remarks/>
        JOL
        
        '''<remarks/>
        AMO
        
        '''<remarks/>
        OBA
        
        '''<remarks/>
        JON
        
        '''<remarks/>
        MIC
        
        '''<remarks/>
        NAM
        
        '''<remarks/>
        HAB
        
        '''<remarks/>
        ZEP
        
        '''<remarks/>
        HAG
        
        '''<remarks/>
        ZEC
        
        '''<remarks/>
        MAL
        
        '''<remarks/>
        MAT
        
        '''<remarks/>
        MRK
        
        '''<remarks/>
        LUK
        
        '''<remarks/>
        JHN
        
        '''<remarks/>
        ACT
        
        '''<remarks/>
        ROM
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1CO")>  _
        Item1CO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2CO")>  _
        Item2CO
        
        '''<remarks/>
        GAL
        
        '''<remarks/>
        EPH
        
        '''<remarks/>
        PHP
        
        '''<remarks/>
        COL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1TH")>  _
        Item1TH
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2TH")>  _
        Item2TH
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1TI")>  _
        Item1TI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2TI")>  _
        Item2TI
        
        '''<remarks/>
        TIT
        
        '''<remarks/>
        PHM
        
        '''<remarks/>
        HEB
        
        '''<remarks/>
        JAS
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1PE")>  _
        Item1PE
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2PE")>  _
        Item2PE
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1JN")>  _
        Item1JN
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2JN")>  _
        Item2JN
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3JN")>  _
        Item3JN
        
        '''<remarks/>
        JUD
        
        '''<remarks/>
        REV
        
        '''<remarks/>
        TOB
        
        '''<remarks/>
        JDT
        
        '''<remarks/>
        ESG
        
        '''<remarks/>
        ADE
        
        '''<remarks/>
        WIS
        
        '''<remarks/>
        SIR
        
        '''<remarks/>
        BAR
        
        '''<remarks/>
        LJE
        
        '''<remarks/>
        DAG
        
        '''<remarks/>
        S3Y
        
        '''<remarks/>
        SUS
        
        '''<remarks/>
        BEL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1MA")>  _
        Item1MA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2MA")>  _
        Item2MA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3MA")>  _
        Item3MA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("4MA")>  _
        Item4MA
        
        '''<remarks/>
        MAN
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1ES")>  _
        Item1ES
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2ES")>  _
        Item2ES
        
        '''<remarks/>
        PS2
        
        '''<remarks/>
        ODA
        
        '''<remarks/>
        PSS
        
        '''<remarks/>
        JSA
        
        '''<remarks/>
        JDB
        
        '''<remarks/>
        TBS
        
        '''<remarks/>
        SST
        
        '''<remarks/>
        DNT
        
        '''<remarks/>
        BLT
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType
        
        '''<remarks/>
        headline
        
        '''<remarks/>
        remark
        
        '''<remarks/>
        verse
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType1
        
        '''<remarks/>
        headline
        
        '''<remarks/>
        paragraph
        
        '''<remarks/>
        prolog
        
        '''<remarks/>
        remark
        
        '''<remarks/>
        verse
    End Enum
End Namespace
