'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.81.0.
'
Namespace ZefaniaXml2005
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class XMLBIBLE
        
        Private iNFORMATIONField As INFORMATION
        
        Private bIBLEBOOKField() As BIBLEBOOK
        
        Private aPPINFOField() As APPINFO
        
        Private biblenameField As String
        
        Private statusField As ModuleStatus
        
        Private statusFieldSpecified As Boolean
        
        Private versionField As String
        
        Private revisionField As String
        
        Private typeField As ModuleType
        
        Public Sub New()
            MyBase.New
            Me.typeField = ModuleType.xbible
        End Sub
        
        '''<remarks/>
        Public Property INFORMATION() As INFORMATION
            Get
                Return Me.iNFORMATIONField
            End Get
            Set
                Me.iNFORMATIONField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BIBLEBOOK")>  _
        Public Property BIBLEBOOK() As BIBLEBOOK()
            Get
                Return Me.bIBLEBOOKField
            End Get
            Set
                Me.bIBLEBOOKField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("APPINFO")>  _
        Public Property APPINFO() As APPINFO()
            Get
                Return Me.aPPINFOField
            End Get
            Set
                Me.aPPINFOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property biblename() As String
            Get
                Return Me.biblenameField
            End Get
            Set
                Me.biblenameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property status() As ModuleStatus
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
        Public Property revision() As String
            Get
                Return Me.revisionField
            End Get
            Set
                Me.revisionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(ModuleType.xbible)>  _
        Public Property type() As ModuleType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class INFORMATION
        
        Private itemsField() As Object
        
        Private itemsElementNameField() As ItemsChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("contributors", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("coverage", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("creator", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("date", GetType(Date), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date"),  _
         System.Xml.Serialization.XmlElementAttribute("description", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("format", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("identifier", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("language", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("publisher", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("rights", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("source", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("subject", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("title", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("type", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType
        
        '''<remarks/>
        contributors
        
        '''<remarks/>
        coverage
        
        '''<remarks/>
        creator
        
        '''<remarks/>
        [date]
        
        '''<remarks/>
        description
        
        '''<remarks/>
        format
        
        '''<remarks/>
        identifier
        
        '''<remarks/>
        language
        
        '''<remarks/>
        publisher
        
        '''<remarks/>
        rights
        
        '''<remarks/>
        source
        
        '''<remarks/>
        subject
        
        '''<remarks/>
        title
        
        '''<remarks/>
        type
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class BIBLEBOOK
        
        Private itemsField() As CHAPTER
        
        Private bnumberField As String
        
        Private bnameField As String
        
        Private bsnameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CHAPTER")>  _
        Public Property Items() As CHAPTER()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property bnumber() As String
            Get
                Return Me.bnumberField
            End Get
            Set
                Me.bnumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property bname() As String
            Get
                Return Me.bnameField
            End Get
            Set
                Me.bnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property bsname() As String
            Get
                Return Me.bsnameField
            End Get
            Set
                Me.bsnameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class CHAPTER
        
        Private itemsField() As Object
        
        Private cnumberField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CAPTION", GetType(CAPTION)),  _
         System.Xml.Serialization.XmlElementAttribute("MEDIA", GetType(TMedia)),  _
         System.Xml.Serialization.XmlElementAttribute("PROLOG", GetType(PROLOG)),  _
         System.Xml.Serialization.XmlElementAttribute("REMARK", GetType(REMARK)),  _
         System.Xml.Serialization.XmlElementAttribute("VERS", GetType(VERS)),  _
         System.Xml.Serialization.XmlElementAttribute("XREF", GetType(XREF))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property cnumber() As String
            Get
                Return Me.cnumberField
            End Get
            Set
                Me.cnumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class CAPTION
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private vrefField As String
        
        Private countField As String
        
        Private typeField As CaptionType
        
        Private typeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BR", GetType(BR)),  _
         System.Xml.Serialization.XmlElementAttribute("GRAM", GetType(GRAM)),  _
         System.Xml.Serialization.XmlElementAttribute("STYLE", GetType(STYLE)),  _
         System.Xml.Serialization.XmlElementAttribute("SUP", GetType(SUP)),  _
         System.Xml.Serialization.XmlElementAttribute("XREF", GetType(XREF))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property vref() As String
            Get
                Return Me.vrefField
            End Get
            Set
                Me.vrefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property count() As String
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property type() As CaptionType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property typeSpecified() As Boolean
            Get
                Return Me.typeFieldSpecified
            End Get
            Set
                Me.typeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class BR
        
        Private artField As BreakType
        
        Private countField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property art() As BreakType
            Get
                Return Me.artField
            End Get
            Set
                Me.artField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property count() As String
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum BreakType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-nl")>  _
        xnl
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-p")>  _
        xp
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class GRAM
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private strField As String
        
        Private rmacField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BR", GetType(BR)),  _
         System.Xml.Serialization.XmlElementAttribute("GRAM", GetType(GRAM)),  _
         System.Xml.Serialization.XmlElementAttribute("STYLE", GetType(STYLE)),  _
         System.Xml.Serialization.XmlElementAttribute("SUP", GetType(SUP))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property str() As String
            Get
                Return Me.strField
            End Get
            Set
                Me.strField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property rmac() As String
            Get
                Return Me.rmacField
            End Get
            Set
                Me.rmacField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class STYLE
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private cssField As String
        
        Private idField As String
        
        Private fsField As TStyleFix
        
        Private fsFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("GRAM", GetType(GRAM)),  _
         System.Xml.Serialization.XmlElementAttribute("STYLE", GetType(STYLE)),  _
         System.Xml.Serialization.XmlElementAttribute("SUP", GetType(SUP))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property css() As String
            Get
                Return Me.cssField
            End Get
            Set
                Me.cssField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fs() As TStyleFix
            Get
                Return Me.fsField
            End Get
            Set
                Me.fsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fsSpecified() As Boolean
            Get
                Return Me.fsFieldSpecified
            End Get
            Set
                Me.fsFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class SUP
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private artField As SupType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("GRAM", GetType(GRAM)),  _
         System.Xml.Serialization.XmlElementAttribute("STYLE", GetType(STYLE))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property art() As SupType
            Get
                Return Me.artField
            End Get
            Set
                Me.artField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum SupType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-sup")>  _
        xsup
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-sub")>  _
        xsub
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum TStyleFix
        
        '''<remarks/>
        acrostic
        
        '''<remarks/>
        bold
        
        '''<remarks/>
        emphasis
        
        '''<remarks/>
        illuminated
        
        '''<remarks/>
        italic
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("line-through")>  _
        linethrough
        
        '''<remarks/>
        normal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("small-caps")>  _
        smallcaps
        
        '''<remarks/>
        [sub]
        
        '''<remarks/>
        super
        
        '''<remarks/>
        underline
        
        '''<remarks/>
        overline
        
        '''<remarks/>
        capitalize
        
        '''<remarks/>
        uppercase
        
        '''<remarks/>
        lowercase
        
        '''<remarks/>
        divineName
        
        '''<remarks/>
        small
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class XREF
        
        Private vefField As String
        
        Private aixField As String
        
        Private fscopeField As String
        
        Private textField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property vef() As String
            Get
                Return Me.vefField
            End Get
            Set
                Me.vefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property aix() As String
            Get
                Return Me.aixField
            End Get
            Set
                Me.aixField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fscope() As String
            Get
                Return Me.fscopeField
            End Get
            Set
                Me.fscopeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum CaptionType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-h1")>  _
        xh1
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-h2")>  _
        xh2
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-h3")>  _
        xh3
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-h4")>  _
        xh4
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-h5")>  _
        xh5
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-h6")>  _
        xh6
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlRootAttribute("MEDIA", [Namespace]:="", IsNullable:=false)>  _
    Partial Public Class TMedia
        
        Private titleField As String
        
        Private typeField As MediaType
        
        Private typeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property type() As MediaType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property typeSpecified() As Boolean
            Get
                Return Me.typeFieldSpecified
            End Get
            Set
                Me.typeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum MediaType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("m-video")>  _
        mvideo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("m-audio")>  _
        maudio
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("m-picture")>  _
        mpicture
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class PROLOG
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private vrefField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BR", GetType(BR)),  _
         System.Xml.Serialization.XmlElementAttribute("GRAM", GetType(GRAM)),  _
         System.Xml.Serialization.XmlElementAttribute("STYLE", GetType(STYLE)),  _
         System.Xml.Serialization.XmlElementAttribute("SUP", GetType(SUP)),  _
         System.Xml.Serialization.XmlElementAttribute("XREF", GetType(XREF))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property vref() As String
            Get
                Return Me.vrefField
            End Get
            Set
                Me.vrefField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class REMARK
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private vrefField As String
        
        Private artField As String
        
        Private aixField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BR", GetType(BR)),  _
         System.Xml.Serialization.XmlElementAttribute("GRAM", GetType(GRAM)),  _
         System.Xml.Serialization.XmlElementAttribute("STYLE", GetType(STYLE)),  _
         System.Xml.Serialization.XmlElementAttribute("SUP", GetType(SUP)),  _
         System.Xml.Serialization.XmlElementAttribute("XREF", GetType(XREF))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property vref() As String
            Get
                Return Me.vrefField
            End Get
            Set
                Me.vrefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property art() As String
            Get
                Return Me.artField
            End Get
            Set
                Me.artField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property aix() As String
            Get
                Return Me.aixField
            End Get
            Set
                Me.aixField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class VERS
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private vnumberField As String
        
        Private vField As String
        
        Private eField As String
        
        Private aixField As String
        
        Private pField As Boolean
        
        Private pFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BR", GetType(BR)),  _
         System.Xml.Serialization.XmlElementAttribute("GRAM", GetType(GRAM)),  _
         System.Xml.Serialization.XmlElementAttribute("NOTE", GetType(NOTE)),  _
         System.Xml.Serialization.XmlElementAttribute("STYLE", GetType(STYLE)),  _
         System.Xml.Serialization.XmlElementAttribute("SUP", GetType(SUP)),  _
         System.Xml.Serialization.XmlElementAttribute("XREF", GetType(XREF))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property vnumber() As String
            Get
                Return Me.vnumberField
            End Get
            Set
                Me.vnumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="positiveInteger")>  _
        Public Property v() As String
            Get
                Return Me.vField
            End Get
            Set
                Me.vField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property e() As String
            Get
                Return Me.eField
            End Get
            Set
                Me.eField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property aix() As String
            Get
                Return Me.aixField
            End Get
            Set
                Me.aixField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property p() As Boolean
            Get
                Return Me.pField
            End Get
            Set
                Me.pField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pSpecified() As Boolean
            Get
                Return Me.pFieldSpecified
            End Get
            Set
                Me.pFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class NOTE
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private typeField As TNotesFix
        
        Private typeFieldSpecified As Boolean
        
        Private n1Field As TNotesFix
        
        Private n1FieldSpecified As Boolean
        
        Private n2Field As TNotesFix
        
        Private n2FieldSpecified As Boolean
        
        Private n3Field As TNotesFix
        
        Private n3FieldSpecified As Boolean
        
        Private n4Field As TNotesFix
        
        Private n4FieldSpecified As Boolean
        
        Private n5Field As TNotesFix
        
        Private n5FieldSpecified As Boolean
        
        Private exField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BR", GetType(BR)),  _
         System.Xml.Serialization.XmlElementAttribute("GRAM", GetType(GRAM)),  _
         System.Xml.Serialization.XmlElementAttribute("STYLE", GetType(STYLE)),  _
         System.Xml.Serialization.XmlElementAttribute("SUP", GetType(SUP)),  _
         System.Xml.Serialization.XmlElementAttribute("XREF", GetType(XREF))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property type() As TNotesFix
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property typeSpecified() As Boolean
            Get
                Return Me.typeFieldSpecified
            End Get
            Set
                Me.typeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property n1() As TNotesFix
            Get
                Return Me.n1Field
            End Get
            Set
                Me.n1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property n1Specified() As Boolean
            Get
                Return Me.n1FieldSpecified
            End Get
            Set
                Me.n1FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property n2() As TNotesFix
            Get
                Return Me.n2Field
            End Get
            Set
                Me.n2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property n2Specified() As Boolean
            Get
                Return Me.n2FieldSpecified
            End Get
            Set
                Me.n2FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property n3() As TNotesFix
            Get
                Return Me.n3Field
            End Get
            Set
                Me.n3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property n3Specified() As Boolean
            Get
                Return Me.n3FieldSpecified
            End Get
            Set
                Me.n3FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property n4() As TNotesFix
            Get
                Return Me.n4Field
            End Get
            Set
                Me.n4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property n4Specified() As Boolean
            Get
                Return Me.n4FieldSpecified
            End Get
            Set
                Me.n4FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property n5() As TNotesFix
            Get
                Return Me.n5Field
            End Get
            Set
                Me.n5Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property n5Specified() As Boolean
            Get
                Return Me.n5FieldSpecified
            End Get
            Set
                Me.n5FieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ex() As String
            Get
                Return Me.exField
            End Get
            Set
                Me.exField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum TNotesFix
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-studynote")>  _
        xstudynote
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("n-studynote")>  _
        nstudynote
        
        '''<remarks/>
        added
        
        '''<remarks/>
        allusion
        
        '''<remarks/>
        alternative
        
        '''<remarks/>
        background
        
        '''<remarks/>
        citation
        
        '''<remarks/>
        crossReference
        
        '''<remarks/>
        devotional
        
        '''<remarks/>
        encoder
        
        '''<remarks/>
        exegesis
        
        '''<remarks/>
        explanation
        
        '''<remarks/>
        liturgical
        
        '''<remarks/>
        speaker
        
        '''<remarks/>
        study
        
        '''<remarks/>
        translation
        
        '''<remarks/>
        [variant]
        
        '''<remarks/>
        amplified
        
        '''<remarks/>
        changed
        
        '''<remarks/>
        deleted
        
        '''<remarks/>
        implied
        
        '''<remarks/>
        moved
        
        '''<remarks/>
        tenseChange
        
        '''<remarks/>
        commentary
        
        '''<remarks/>
        exposition
        
        '''<remarks/>
        meditation
        
        '''<remarks/>
        outline
        
        '''<remarks/>
        rebuttal
        
        '''<remarks/>
        sermon
        
        '''<remarks/>
        studyGuide
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("translation")>  _
        translation1
        
        '''<remarks/>
        transChange
        
        '''<remarks/>
        tr
        
        '''<remarks/>
        trao
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class APPINFO
        
        Private anyField As System.Xml.XmlElement
        
        Private appidField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property appid() As String
            Get
                Return Me.appidField
            End Get
            Set
                Me.appidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum ModuleStatus
        
        '''<remarks/>
        v
        
        '''<remarks/>
        w
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0"),  _
     System.SerializableAttribute()>  _
    Public Enum ModuleType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-bible")>  _
        xbible
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-quran")>  _
        xquran
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-mormon")>  _
        xmormon
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-other")>  _
        xother
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("x-cult")>  _
        xcult
    End Enum
End Namespace
